name: Pokedex CI/CD

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

        # Build and test frontend
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            
            - name: Install dependencies, build frontend
              run: | 
                cd frontend
                npm install
                npm run build

        # Build and test backend
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.11'

            - name: Install dependencies and test backend
              run: | 
                cd backend
                pip install -r requirements.txt
                pytest --rootdir=/home/runner/work/pokedex/pokedex/backend

        # Create EB Zip
            - name: Zip app
              run: zip -r app.zip backend frontend .ebextensions README.md

        # Deploy to AWS EB
            - name: Deploy to AWS
              uses: einaregilsson/beanstalk-deploy@v21
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                application_name: Pokedex
                environment_name: Pokedex-env
                region: us-east-1
                version_label: ${{ github.run_id }}
                deployment_package: app.zip